<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Capítulo 2 Introducción | Análisis Estadístico de Datos Financieros con R</title>
  <meta name="description" content="Libro de Análisis Estadístico de Datos Financieros con R">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Capítulo 2 Introducción | Análisis Estadístico de Datos Financieros con R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Libro de Análisis Estadístico de Datos Financieros con R" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 2 Introducción | Análisis Estadístico de Datos Financieros con R" />
  
  <meta name="twitter:description" content="Libro de Análisis Estadístico de Datos Financieros con R" />
  

<meta name="author" content="Oswaldo Navarrete Carreño, María Alexandra Chávez">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="index.html">
<link rel="next" href="pruebas-de-hipotesis.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Análisis Estadístico de Datos Financieros Con R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> ¿A quién va dirigido este libro?</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#instalando-r-y-rstudio"><i class="fa fa-check"></i><b>1.1</b> Instalando R Y Rstudio</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introducción</a><ul>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#estadistica-descriptiva-e-inferencial"><i class="fa fa-check"></i><b>2.1</b> Estadística descriptiva e inferencial</a></li>
<li class="chapter" data-level="2.2" data-path="intro.html"><a href="intro.html#tipos-de-variables"><i class="fa fa-check"></i><b>2.2</b> Tipos de Variables</a><ul>
<li class="chapter" data-level="2.2.1" data-path="intro.html"><a href="intro.html#niveles-de-medicion"><i class="fa fa-check"></i><b>2.2.1</b> Niveles de medición</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="intro.html"><a href="intro.html#primerR"><i class="fa fa-check"></i><b>2.3</b> Primeros pasos en R</a></li>
<li class="chapter" data-level="2.4" data-path="intro.html"><a href="intro.html#medidas-de-tendencia-central"><i class="fa fa-check"></i><b>2.4</b> Medidas de Tendencia Central</a><ul>
<li class="chapter" data-level="2.4.1" data-path="intro.html"><a href="intro.html#media"><i class="fa fa-check"></i><b>2.4.1</b> Media</a></li>
<li class="chapter" data-level="2.4.2" data-path="intro.html"><a href="intro.html#mediana"><i class="fa fa-check"></i><b>2.4.2</b> Mediana</a></li>
<li class="chapter" data-level="2.4.3" data-path="intro.html"><a href="intro.html#moda"><i class="fa fa-check"></i><b>2.4.3</b> Moda</a></li>
<li class="chapter" data-level="2.4.4" data-path="intro.html"><a href="intro.html#trabajamos-con-la-media-o-la-mediana"><i class="fa fa-check"></i><b>2.4.4</b> ¿trabajamos con la media o la mediana?</a></li>
<li class="chapter" data-level="2.4.5" data-path="intro.html"><a href="intro.html#calculo-de-las-medidas-de-tendencia-central-en-r"><i class="fa fa-check"></i><b>2.4.5</b> Cálculo de las medidas de tendencia central en R</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="intro.html"><a href="intro.html#medidas-de-posicion-cuantiles"><i class="fa fa-check"></i><b>2.5</b> Medidas de posición (Cuantiles)</a><ul>
<li class="chapter" data-level="2.5.1" data-path="intro.html"><a href="intro.html#tipos-de-cuantiles"><i class="fa fa-check"></i><b>2.5.1</b> Tipos de Cuantiles</a></li>
<li class="chapter" data-level="2.5.2" data-path="intro.html"><a href="intro.html#calculo-de-cuantiles"><i class="fa fa-check"></i><b>2.5.2</b> Cálculo de cuantiles</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="intro.html"><a href="intro.html#medidas-de-dispersion"><i class="fa fa-check"></i><b>2.6</b> Medidas de dispersión</a></li>
<li class="chapter" data-level="2.7" data-path="intro.html"><a href="intro.html#tablas-de-frecuencia"><i class="fa fa-check"></i><b>2.7</b> Tablas de frecuencia</a><ul>
<li class="chapter" data-level="2.7.1" data-path="intro.html"><a href="intro.html#variables-cualitativas"><i class="fa fa-check"></i><b>2.7.1</b> Variables Cualitativas</a></li>
<li class="chapter" data-level="2.7.2" data-path="intro.html"><a href="intro.html#variables-cuantitativas"><i class="fa fa-check"></i><b>2.7.2</b> Variables Cuantitativas</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="intro.html"><a href="intro.html#tablas-de-contingencia"><i class="fa fa-check"></i><b>2.8</b> Tablas de Contingencia</a></li>
<li class="chapter" data-level="2.9" data-path="intro.html"><a href="intro.html#graficos-y-visualizacion"><i class="fa fa-check"></i><b>2.9</b> Gráficos y Visualización</a><ul>
<li class="chapter" data-level="2.9.1" data-path="intro.html"><a href="intro.html#histogramas"><i class="fa fa-check"></i><b>2.9.1</b> Histogramas</a></li>
<li class="chapter" data-level="2.9.2" data-path="intro.html"><a href="intro.html#diagramas-de-caja-y-valores-atipicos"><i class="fa fa-check"></i><b>2.9.2</b> Diagramas de Caja y valores atípicos</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="pruebas-de-hipotesis.html"><a href="pruebas-de-hipotesis.html"><i class="fa fa-check"></i><b>3</b> Pruebas de Hipótesis</a></li>
<li class="chapter" data-level="4" data-path="methods.html"><a href="methods.html"><i class="fa fa-check"></i><b>4</b> Regresión</a></li>
<li class="chapter" data-level="5" data-path="analisis-factorial.html"><a href="analisis-factorial.html"><i class="fa fa-check"></i><b>5</b> Análisis Factorial</a><ul>
<li class="chapter" data-level="5.1" data-path="analisis-factorial.html"><a href="analisis-factorial.html#analisis-de-fiabilidad"><i class="fa fa-check"></i><b>5.1</b> Análisis de Fiabilidad</a></li>
<li class="chapter" data-level="5.2" data-path="analisis-factorial.html"><a href="analisis-factorial.html#evaluacion-de-analisis-factorial"><i class="fa fa-check"></i><b>5.2</b> Evaluación de Análisis Factorial</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="algo-de-series-de-tiempo.html"><a href="algo-de-series-de-tiempo.html"><i class="fa fa-check"></i><b>6</b> Algo de series de tiempo</a></li>
<li class="chapter" data-level="" data-path="bibliografia.html"><a href="bibliografia.html"><i class="fa fa-check"></i>Bibliografía</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Análisis Estadístico de Datos Financieros con R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="intro" class="section level1">
<h1><span class="header-section-number">Capítulo 2</span> Introducción</h1>
<p>En nuestra vida diaria es común escuchar el término <strong>estadística</strong>, las tasas de desempleo, el índice de pobreza, el saldo promedio de nuestra cuenta de ahorros, el número de goles realizados en la LigaPro durante el fin de semana, etc. Aunque no es una forma incorrecta de ver las estadísticas, en este texto se pensará a la estadística como un conjunto de métodos que se utilizan para <strong>recoger, clasificar, resumir, organizar, presentar, analizar e interpretar información numérica</strong></p>
<p>En las empresas la estadística es usada para tomar decisiones como los productos y las cantidades que deben ser producidas, la frecuencia con la que una maquinaria debe recibir mantenimiento, el tamaño del inventario, la forma de distribuir los productos, y casi todos los aspectos relativos a sus operaciones. En el estudio de las finanzas, la contabilidad, la economía y otras ciencias sociales la motivación para usar estadística radica en entender como funcionan los sistemas económicos, financieros o contables.</p>
<div id="estadistica-descriptiva-e-inferencial" class="section level2">
<h2><span class="header-section-number">2.1</span> Estadística descriptiva e inferencial</h2>
<p>El uso de la estadística puede ser de dos formas. La primera, cuando se describen y se presentan los datos. Y la segunda es cuando los datos son utilizados para hacer inferencias sobre características del ambiente o entorno de donde se seleccionaron los datos o sobre el mecanismo subyacente que generó los datos. La primera forma recibe el nombre de <strong>estadística descriptiva</strong> y la segunda se conoce como <strong>estadística inferencial</strong></p>
<p>En la estadística descriptiva se utilizan métodos numéricos y gráficos para encontrar patrones y características de los datos a fin de resumir la información y presentarla de una forma significativa. Mientras que en la estadística inferencial se utilizan los daots para tomar decisiones, hacer estimaciones, pronósticos o predicciones y generalizaciones sobre el entorno del que fueron obtenidos los datos o el proceso que los generó.</p>
<p>Sea en estadística descriptiva o en estadística inferencial, el primer paso siempre va a ser obtener información de alguna característica, medida o valor que nos interese de un grupo de elementos. Esa característica, medida o valor de interés para el investigador recibe el nombre de <strong>variable</strong>.</p>
</div>
<div id="tipos-de-variables" class="section level2">
<h2><span class="header-section-number">2.2</span> Tipos de Variables</h2>
<p>Muchos autores presentan algunas clasificaciones para las variables, sin embargo vamos a trabajar con una clasificación que se ajusta a las necesidades de la investigación en las áreas de nuestro interés. Según esta clasificación hay dos grandes grupos de variables: cuantitativas y cualitativas. Las primeras son las que toman valores <strong>numéricos</strong>. Mientras que las cualitativas toman valores que describen una <strong>cualidad</strong> o <strong>característica</strong>.</p>
<p>Las variables cuantitativas se clasifican a la vez en <strong>continuas</strong> que se presentan cuando las observaciones pueden tomar cualquier valor dentro de un subconjunto de los números reales, ejemplos de variables cuantitativas continuas son: edad, altura, temperatura y peso. Las <strong>discretas</strong> son aquellas cuya característica principal es que las observaciones pueden tomar un valor basado en un recuento de un conjunto de valores enteros distintos. Ejemplos de variables cuantitativas discretas son: número de hijos, número de comprobantes de venta emitidos en un mes, número de clientes haciendo fila durante una hora en un banco.</p>
<div id="niveles-de-medicion" class="section level3">
<h3><span class="header-section-number">2.2.1</span> Niveles de medición</h3>
<p>Hay cuatro niveles de medición <strong>ordinal</strong>, <strong>nominal</strong>, <strong>intervalo</strong> y de <strong>radio</strong>. En el nivel ordinal las observaciones toman valores que se ordenan o clasifican de forma lógica, por ejemplo las tallas de ropa (pequeña, media, grande, extra grande), la frecuencia con la que se hace una actividad (nunca, casi nunca, a veces, casi siempre, siempre). Por otro lado, en el nivel nominal las observaciones toman valores que no se pueden organizar de forna lógica, por ejemplo el sexo, el color de ojos, la marca de ropa favorita.</p>
<p>En el nivel de intervalo existe diferencia significativa entre valores pero el cero no representa la ausencia de la característica un ejemplo es la temperatura medida en grados Farenheit. Finalmente en el nivel de razón el 0 es significativo y la razón entre dos números es significativa, un ejemplo es la temperatura medida en grados Kelvin.</p>
</div>
</div>
<div id="primerR" class="section level2">
<h2><span class="header-section-number">2.3</span> Primeros pasos en R</h2>
<p>Una vez instalado R y RStudio, abrimos Rstudio para comenzar a trabajar. La ventana de RStudio se ve como se muestra en la figura <a href="intro.html#fig:rstudio1">2.1</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:rstudio1"></span>
<img src="rstudio1.png" alt="Ventana de RStudio" width="50%" />
<p class="caption">
Figura 2.1: Ventana de RStudio
</p>
</div>
<p>Lo primero que debemos hacer es abrir un nuevo script, un script de R es simplemente un archivo de texto que contiene (casi) todos los comandos que se escribirían en la línea de comandos de R, para esto en la barra de menú seguimos la secuencia <strong>File, New File, R Script</strong> o desde el teclado con la combinación <em>Ctrl + Shift + N</em>, en este archivo iremos escribiendo todos los comandos que vamos a trabajar. En la figura <a href="intro.html#fig:rstudio2">2.2</a> se aprecia un script abierto.</p>
<div class="figure" style="text-align: center"><span id="fig:rstudio2"></span>
<img src="rstudio2.png" alt="Ventana de RStudio con Script" width="50%" />
<p class="caption">
Figura 2.2: Ventana de RStudio con Script
</p>
</div>
<p>Para empezar a aprender en el script vamos a escribir <code>3+2</code> y ejecutamos esto con la combinación de teclas <strong>Ctrl + Enter</strong> el resultado obviamente es 5. Ahora ingresaremos un conjunto de valores y los almacenaremos en una variable, para almacenar algo en una variable se puede usar <code>&lt;-</code> o <code>=</code>. En la variable <code>x</code> almacenaremos un conjunto de 8 observaciones escribiendo el código:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">3</span>,<span class="dv">7</span>,<span class="dv">9</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">10</span>) </code></pre></div>
<p>Recuerde que este código se ejecuta con la combinación de teclas <strong>Ctrl + Enter</strong>. Para poder realizar análisis estadístico, es necesario cargar nuestros datos en el programa. R acepta algunos formatos de archivos, como por ejemplo archivos de Excel, archivos de valores separados por coma, archivos de texto e inclusive archivos de otros programas como SPSS. Lo más usual es trabajar con archvo de valores separados por coma es decir con extensión <code>.csv</code>, estos archivos <code>csv</code> se generan cuando el investigador recolecta la información, la almacena en un archivo de Excel o alguna otra hoja de cálculo y la guarda como un archivo de valores separados por coma.</p>
<p>Para trabajar de forma eficiente con R, se recomienda comenzar por fijar un directorio de trabajo donde deben estar guardados nuestros archivos en el formato que sea de nuestra preferencia. Una forma de hacerlo es desde la barra de menú <strong>Session, Set Working Directory, Choose Directory</strong> o desde el teclado con la combinación <strong>Ctrl+Shift+H</strong>, o con la función <code>setwd(&quot;rutadelarchivo&quot;)</code>.</p>
<p>En este primer ejercicio trabajaremos con el archivo <em>cap2_big4_size.csv</em>. Los datos serán guardados en una variable llamada <code>datos1</code>, usaremos la función <code>read.csv()</code> para leer los datos. La función <code>read.csv()</code> recibe las instrucciones <code>read.csv(&quot;archivo&quot;, header=T, sep=&quot;;&quot;,dec=&quot;,&quot;)</code>. La opción <code>&quot;archivo&quot;</code> indica el nombre del archivo, <code>header=T</code> o <code>header=F</code> permite indicar si las columnas tienen un encabezado que las identifique, <code>sep=&quot;;&quot;</code> sirve para indicar cual es el separador presente en nuestro archivo en algunas ocasiones ocurre que un archivo de valores separado por coma en realidad tiene sus valores separados por un punto y cona esto generalmente ocurre cuando el sistema utiliza, como en este caso, la coma como separador decimal y finalmente la opción <code>dec=&quot;,&quot;</code> sirve para indicar que el separador decimal es la coma.</p>
<p>Una característica de R es que permite acceder a la ayuda sobre las funciones, esto se hace escribiendo <code>?funcion</code> por ejemplo si queremos la ayuda de la función <code>read.csv</code> simplemente escribimos <code>?read.csv</code> en el panel ubicado en la parte inferior derecha se desplegará la ayuda de la función. Con la particularidad de que la ayuda se despliega en inglés lo que no debería ser problema para un buen investigador.</p>
<p>El archivo que vamos a analizar contiene los activos, la utilidad, las ventas y el patrimonio de una muestra de empresas tomada de los registros de la Superintendencia de Compañías. Además en el conjunto de datos se indica si la empresa ha sido auditada por una de las 4 firmas auditoras consideradas las más grandes o también llamadas <em><em>Big Four</em></em>. En la <a href="intro.html#tab:tabla1">2.1</a> se muestran las 10 primeras observaciones de nuestro conjunto de datos.</p>
<table>
<caption>
<span id="tab:tabla1">Tabla 2.1: </span>Primeras 10 observaciones
</caption>
<thead>
<tr>
<th style="text-align:right;">
EXPMUESTRA
</th>
<th style="text-align:right;">
BIG4
</th>
<th style="text-align:right;">
ACTIVOS
</th>
<th style="text-align:right;">
UTILIDAD
</th>
<th style="text-align:right;">
VTAS
</th>
<th style="text-align:right;">
PAT
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
85
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
73315618
</td>
<td style="text-align:right;">
7522758.7
</td>
<td style="text-align:right;">
191474544
</td>
<td style="text-align:right;">
39382529
</td>
</tr>
<tr>
<td style="text-align:right;">
100121
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
21052702
</td>
<td style="text-align:right;">
-122898.5
</td>
<td style="text-align:right;">
132585022
</td>
<td style="text-align:right;">
1577764
</td>
</tr>
<tr>
<td style="text-align:right;">
45178
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
10468672
</td>
<td style="text-align:right;">
536876.9
</td>
<td style="text-align:right;">
13974269
</td>
<td style="text-align:right;">
4312094
</td>
</tr>
<tr>
<td style="text-align:right;">
51193
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
4130483
</td>
<td style="text-align:right;">
455759.4
</td>
<td style="text-align:right;">
8670153
</td>
<td style="text-align:right;">
1858990
</td>
</tr>
<tr>
<td style="text-align:right;">
47598
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
23507401
</td>
<td style="text-align:right;">
266370.5
</td>
<td style="text-align:right;">
18555609
</td>
<td style="text-align:right;">
7137609
</td>
</tr>
<tr>
<td style="text-align:right;">
31720
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
7220312
</td>
<td style="text-align:right;">
437718.3
</td>
<td style="text-align:right;">
16097135
</td>
<td style="text-align:right;">
4002154
</td>
</tr>
<tr>
<td style="text-align:right;">
46189
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
14526822
</td>
<td style="text-align:right;">
1206400.9
</td>
<td style="text-align:right;">
12281188
</td>
<td style="text-align:right;">
5015806
</td>
</tr>
<tr>
<td style="text-align:right;">
9731
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
8539445
</td>
<td style="text-align:right;">
367848.1
</td>
<td style="text-align:right;">
10844918
</td>
<td style="text-align:right;">
2232339
</td>
</tr>
<tr>
<td style="text-align:right;">
4619
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
2605059
</td>
<td style="text-align:right;">
-22438.4
</td>
<td style="text-align:right;">
6244589
</td>
<td style="text-align:right;">
1366610
</td>
</tr>
<tr>
<td style="text-align:right;">
102434
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
23975816
</td>
<td style="text-align:right;">
790265.6
</td>
<td style="text-align:right;">
40612649
</td>
<td style="text-align:right;">
8754369
</td>
</tr>
</tbody>
</table>
<p>Sin más preámbulos, empecemos a trabajar. Recapitulando, primero configuraremos el directorio de trabajo, luego cargaremos el archivo indicado. Finalmente usamos la función <code>str()</code>, la que nos permite obtener la descripción de la estructura de los datos.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">setwd</span>(<span class="st">&quot;C:/Users/onava_000/OneDrive/libro_mc/estadistica&quot;</span>)
big4size &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;cap2_big4_size.csv&quot;</span>,<span class="dt">header=</span><span class="ot">TRUE</span>,<span class="dt">sep=</span><span class="st">&quot;;&quot;</span>,<span class="dt">dec=</span><span class="st">&quot;,&quot;</span>)
<span class="kw">str</span>(big4size)</code></pre></div>
<pre><code>## &#39;data.frame&#39;:    2256 obs. of  6 variables:
##  $ EXPMUESTRA: int  85 100121 45178 51193 47598 31720 46189 9731 4619 102434 ...
##  $ BIG4      : int  1 0 0 0 0 0 0 0 0 0 ...
##  $ ACTIVOS   : num  73315618 21052702 10468672 4130483 23507401 ...
##  $ UTILIDAD  : num  7522759 -122898 536877 455759 266371 ...
##  $ VTAS      : num  1.91e+08 1.33e+08 1.40e+07 8.67e+06 1.86e+07 ...
##  $ PAT       : num  39382529 1577764 4312094 1858990 7137609 ...</code></pre>
<p>En la primera línea de los resultados se observa la salida <code>'data.frame':    2256 obs. of  6 variables:</code> esto nos indica que nuestro <em>marco de datos (data frame)</em> tiene 2256 observaciones y 6 variables. Con respecto a las variables tenemos 6 variables que a continuación se describen y se explican los resultados obtenidos con la función.</p>
<ul>
<li><code>EXPMUESTRA</code>: esta variable es de tipo entera (INT) y almacena el expediente de la empresa. Aunque la variable tiene valores numéricos, no es una variable cuantitativa sino cualitativa “Expediente de la Empresa”</li>
<li><code>BIG4</code>: esta variable es de tipo entera, y ha sido codificada con 1 si la empresa fue auditada por una Big Four y 0 si no. Podemos cambiar esta codificación por “Sí” y “No” en lugar de “1” y “0”, más adelante aprendemos como hacerlo. Al igual que la variable anterior aunque tiene valores numéricos, no es una variable cuantitativa sino cualitativa, dejamos al lector la reflexión en este particular.</li>
<li><code>ACTIVOS</code>: contiene el valor de los activos totales de la empresa. Es de tipo <code>num</code> porque permite el uso de decimales. Corresponde a una variable cuantitativa continua.</li>
<li><code>UTILIDAD</code>: contiene el valor de la utildad de la empresa.</li>
<li><code>VTAS</code>: contiene el valor de las ventas de la empresa.</li>
<li><code>PAT</code>: contiene el valor del patrimonio de la empresa.</li>
</ul>
<p>Los paquetes de R son colecciones de funciones y conjuntos de datos desarrollados por la comunidad de usuarios, los paquetes aumentan el poder de R mejorando las funcionalidades existentes en la base de R, o añadiendo nuevas funcionalidades. En este texto trabajaremos con algunos de los paquetes desarrollados por el equipo de RStudio, una descripción detallada de estos paquetes puede ser encontrada en <a href="https://www.rstudio.com/products/rpackages/" class="uri">https://www.rstudio.com/products/rpackages/</a>. . Comenzaremos por instalar el paquete <code>dplyr</code>, este paquete tiene funciones que permiten realizar facilmente manipulaciones de datos. Para instalar un paquete se utiliza la función <code>install.packages(&quot;paquete&quot;)</code>. Una vez instalado el paquete, se carga el paquete utilizando la función <code>library(paquete)</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">install.packages</span>(<span class="st">&quot;dplyr&quot;</span>)</code></pre></div>
<p>La primera manipulación que vamos a realizar es la creación de nuevas variables con el paquete <code>dplyr</code>. En nuestros datos cargados en el conjunto de datos <code>datos1</code> vamos a crear tres variables nuevas <strong>ROA</strong>, <strong>ROS</strong> y <strong>ROE</strong>. Recordemos que el <strong>Retorno sobre activos</strong> ( <strong>ROA</strong>, Return on Assets) se lo calcula como la razón entre la utilidad y los activos como se ve en la ecuación <a href="intro.html#eq:roa">(2.1)</a>. En las ecuaciones <a href="intro.html#eq:ros">(2.2)</a> y <a href="intro.html#eq:roe">(2.3)</a> se dan las expresiones para calcular el <strong>Retorno sobre ventas</strong> ( <strong>ROS</strong> Return on Sales) y el <strong>Retorno sobre el Patrimonio</strong> ( <strong>ROE</strong> Return on Equity)</p>
<span class="math display" id="eq:roa">\[\begin{equation} 
  ROA = \dfrac{Utilidad}{Activos}
  \tag{2.1}
\end{equation}\]</span>
<span class="math display" id="eq:ros">\[\begin{equation} 
  ROS = \dfrac{Utilidad}{Ventas}
  \tag{2.2}
\end{equation}\]</span>
<span class="math display" id="eq:roe">\[\begin{equation} 
  ROE = \dfrac{Utilidad}{Patrimonio}
  \tag{2.3}
\end{equation}\]</span>
<p>Una característica importante de <code>dplyr</code> es el uso del operador <code>%&gt;%</code>. Cada transformación u operación en los datos se separa por el operador <code>%&gt;%</code>. La primera función de <code>dplyr</code> que usaremos es <code>mutate()</code>, básicamente esta función permite crear nuevas variables.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dplyr)
big4size &lt;-<span class="st"> </span>big4size <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(
    <span class="dt">ROA =</span> UTILIDAD<span class="op">/</span>ACTIVOS,
    <span class="dt">ROS =</span> UTILIDAD<span class="op">/</span>VTAS,
    <span class="dt">ROE =</span> UTILIDAD<span class="op">/</span>PAT
  )
<span class="kw">str</span>(big4size)</code></pre></div>
<pre><code>## &#39;data.frame&#39;:    2256 obs. of  9 variables:
##  $ EXPMUESTRA: int  85 100121 45178 51193 47598 31720 46189 9731 4619 102434 ...
##  $ BIG4      : int  1 0 0 0 0 0 0 0 0 0 ...
##  $ ACTIVOS   : num  73315618 21052702 10468672 4130483 23507401 ...
##  $ UTILIDAD  : num  7522759 -122898 536877 455759 266371 ...
##  $ VTAS      : num  1.91e+08 1.33e+08 1.40e+07 8.67e+06 1.86e+07 ...
##  $ PAT       : num  39382529 1577764 4312094 1858990 7137609 ...
##  $ ROA       : num  0.10261 -0.00584 0.05128 0.11034 0.01133 ...
##  $ ROS       : num  0.039289 -0.000927 0.038419 0.052566 0.014355 ...
##  $ ROE       : num  0.191 -0.0779 0.1245 0.2452 0.0373 ...</code></pre>
<p>En las últimas líneas de la salida de R, se observa que ahora en el conjunto de datos existen ahora tres nuevas variables. En la próxima sección seguiremos trabajando con el mismo conjunto de datos.</p>
</div>
<div id="medidas-de-tendencia-central" class="section level2">
<h2><span class="header-section-number">2.4</span> Medidas de Tendencia Central</h2>
<p>Una medida de tendencia central, es una medida de resumen que intenta describir un conjunto completo de datos con un único valor que representa la mitad o centro de la distribución.</p>
<p>Las tres medidas de tendencia central principales son la media la mediana y la moda.</p>
<div id="media" class="section level3">
<h3><span class="header-section-number">2.4.1</span> Media</h3>
<p>La media se la calcula como la suma de todos los valores de una variable dividido para el número de valores. En la ecuación <a href="intro.html#eq:mean">(2.4)</a> se muestra la fórmula para calcular la media.</p>
<span class="math display" id="eq:mean">\[\begin{equation} 
  \bar{x} = \dfrac{\sum_{i=1}^{n}x_i}{n}
  \tag{2.4}
\end{equation}\]</span>
<p>La media tiene algunas propiedades que a continuación se detallan:</p>
<ul>
<li>Si a cada valor <span class="math inline">\(x_i\)</span> de una distribución con media <span class="math inline">\(\bar{x}\)</span> se le suma un valor constante <span class="math inline">\(k \in \mathbb{R}\)</span>, la nueva media es <span class="math inline">\(\bar{x}+k\)</span></li>
<li>Si a cada valor <span class="math inline">\(x_i\)</span> de una distribución con media <span class="math inline">\(\bar{x}\)</span> se lo multiplica por un valor constante <span class="math inline">\(k \in \mathbb{R}\)</span>, la nueva media es <span class="math inline">\(k\bar{x}\)</span></li>
<li>Si a cada valor <span class="math inline">\(x_i\)</span> de una distribución con media <span class="math inline">\(\bar{x}\)</span> se lo divide por un valor constante <span class="math inline">\(k \neq 0 \in \mathbb{R}\)</span>, la nueva media es <span class="math inline">\(\dfrac{\bar{x}}{k}\)</span></li>
</ul>
<p>Las ventajas de usar la media son:</p>
<ul>
<li>Es fácil de entender y calcular</li>
<li>No se ve afectada mayormente por fluctuaciones productos del muestreo</li>
<li>Toma en cuenta todos los valores de la variable</li>
</ul>
<p>Las desventajas de usar la media son:</p>
<ul>
<li>Es muy sensible a la presencia de pocos valores muy pequeños o muy grandes, dicho de otra forma la media es sensible a valores aberrantes.</li>
<li>No se puede calcular por inspección.</li>
</ul>
</div>
<div id="mediana" class="section level3">
<h3><span class="header-section-number">2.4.2</span> Mediana</h3>
<p>La mediana es el valor central en una distribución cuando se ordenan los valores de forma ascendente o descendente. El valor de la mediana depende entonces del número de valores presentes en la variable. Definamos como <span class="math inline">\(\left\{ X \right \}\)</span> al conjunto de datos ordenado, y sea <span class="math inline">\(\left \{ X \right \}_i\)</span> el valor i-ésimo del conjunto <span class="math inline">\(\left \{ X \right \}\)</span> entonces la mediana <span class="math inline">\(Me\)</span> se define como</p>
<span class="math display" id="eq:median">\[\begin{equation}
Me = \begin{cases} 
      \left \{ X \right\}_{\frac{n+1}{2}} &amp; ; n \quad \textrm{impar}  \\
      \dfrac{\left \{ X  \right \}_{\frac{n}{2}} + \left \{ X  \right \}_{\frac{n}{2}+1} }{2} &amp; ; n \quad \textrm{par}
   \end{cases}
   \tag{2.5}
\end{equation}\]</span>
<p>Lo escrito en la ecuación <a href="intro.html#eq:median">(2.5)</a> se puede expresar de la siguiente forma: si el número de datos es impar, la mediana es igual al valor central de la distribución y si el número de datos es par, la mediana es igual al promedio de los valores centrales de la distribución.</p>
<p>Las ventajas de usar la mediana son:</p>
<ul>
<li>Es fácil de calcular y comprender</li>
<li>No se ve afectada por valores extremos</li>
<li>Se puede determinar para escalas ordinales, nominales, de razón e intervalo</li>
</ul>
<p>Las desventajas de usar la mediana son:</p>
<ul>
<li>No toma en cuenta el valor exacto de cada dato y por tanto no usa toda la información disponible.</li>
<li>Si se agrupan los valores de dos grupos, la mediana de cada grupo no puede ser expresada en términos del grupo agrupado.</li>
</ul>
</div>
<div id="moda" class="section level3">
<h3><span class="header-section-number">2.4.3</span> Moda</h3>
<p>La moda es definida como el valor que ocurre con mayor frecuencia en los datos. Algunos conjuntos de datos no tienen moda porque cada valor ocurre solo una vez. Hay conjuntos de datos que tienen más de una moda, si tienen 2 modas reciben el nombre de bimodal y se acostumbra que si tiene más de 3 modas se la llama multimodal.</p>
<p>Las ventajas de usar la moda son:</p>
<ul>
<li>Puede ser usada para datos con escala nominal</li>
<li>Es sencilla de calcular</li>
</ul>
<p>La desventaja de la moda es:</p>
<ul>
<li>No es usada en análisis estadístico debido a que no está definida algebraicamente y la fluctuación en la frecuencia de las observaciones es mayor cuando el tamaño de la muestra es pequeña.</li>
</ul>
</div>
<div id="trabajamos-con-la-media-o-la-mediana" class="section level3">
<h3><span class="header-section-number">2.4.4</span> ¿trabajamos con la media o la mediana?</h3>
<p>La media es considerada generalmente la mejor medida de tendencia central y la más usada. Sin embargo, hay situaciones donde las otras medidas de tendencia central son preferidas.</p>
<p>La mediana es preferida a la media cuando:</p>
<ul>
<li>Hay valores extremos en la distribución</li>
<li>Hay valores indeterminados</li>
<li>Los datos son medidos en una escala ordinal</li>
</ul>
<p>La moda es la medida preferida cuando los datos son medidos en una escala nominal.</p>
</div>
<div id="calculo-de-las-medidas-de-tendencia-central-en-r" class="section level3">
<h3><span class="header-section-number">2.4.5</span> Cálculo de las medidas de tendencia central en R</h3>
<p>Para calcular la media y la mediana se utilizan las funciones <code>mean()</code> y <code>median()</code> respectivamente, estas dos funciones vienen cargadas con los paquetes base de R. Para calcular la moda usaremos la función <code>Mode()</code> del paquete <code>DescTools</code>, recuerde que para instalar un paquete se utiliza la función <code>install.packages()</code>.</p>
<p>En el siguiente ejemplo se obtiene la media de los activos de las empresas. como solamente necesitamos una variable del conjunto de datos usamos el operador <code>$</code>, el funcionamiento de este operador es <code>data.frame$variable</code> es decir indicamos el conjunto de datos del que llamamos la variable y después del operador <code>$</code> indicamos la variable que vamos a trabajar.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mean</span>(big4size<span class="op">$</span>ACTIVOS)</code></pre></div>
<pre><code>## [1] 44064165</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">median</span>(big4size<span class="op">$</span>ACTIVOS)</code></pre></div>
<pre><code>## [1] 10326361</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(DescTools)
<span class="kw">Mode</span>(big4size<span class="op">$</span>ACTIVOS)</code></pre></div>
<pre><code>## [1]  55996406 628446149</code></pre>
<p>En el resultado de la moda se obtienen 2 valores. Es decir que existen dos valores que se repiten más veces o tienen mayor frecuencia. Cuando se realiza investigación es común desear hacer una tabla con las estadísticas descriptivas de los datos. El paquete <code>dplyr</code> permite realizar tablas que resuman las variables de forma sencilla con la función <code>summarise()</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">big4size <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">PROM.ACTIVOS =</span> <span class="kw">mean</span>(ACTIVOS),
            <span class="dt">PROM.UTILIDAD =</span> <span class="kw">mean</span>(UTILIDAD),
            <span class="dt">PROM.VTAS =</span> <span class="kw">mean</span>(VTAS),
            <span class="dt">MEDIAN.ACTIVOS =</span> <span class="kw">median</span>(ACTIVOS),
            <span class="dt">MEDIAN.UTILIDAD =</span> <span class="kw">median</span>(UTILIDAD),
            <span class="dt">MEDIAN.VTAS =</span> <span class="kw">median</span>(VTAS)
            )</code></pre></div>
<pre><code>##   PROM.ACTIVOS PROM.UTILIDAD PROM.VTAS MEDIAN.ACTIVOS MEDIAN.UTILIDAD
## 1     44064165       4250664  50555030       10326361        350642.1
##   MEDIAN.VTAS
## 1     9190661</code></pre>
</div>
</div>
<div id="medidas-de-posicion-cuantiles" class="section level2">
<h2><span class="header-section-number">2.5</span> Medidas de posición (Cuantiles)</h2>
<p>Las medidas de posición no central permiten conocer otros puntos característicos de la distribución que no son los valores centrales. Entre las medidas de posición no central más importantes están los cuantiles. El término cuantil fue usado por primera vez por Kendall en 1940.</p>
<p>El cuantil de orden p de una distribución con <span class="math inline">\(0&lt;p&lt;1\)</span> es el valor <span class="math inline">\(x_{i}\)</span> de la variable <span class="math inline">\(X\)</span> que marca un corte de modo que una proporción <span class="math inline">\(p\)</span> o un porcentaje <span class="math inline">\(100p\)</span>% de valores de la población es menor o igual que <span class="math inline">\(x_{i}\)</span> Por ejemplo el cuantil de orden <span class="math inline">\(0.35\)</span> dejaría un 35% de valores por debajo de él.</p>
<div id="tipos-de-cuantiles" class="section level3">
<h3><span class="header-section-number">2.5.1</span> Tipos de Cuantiles</h3>
<ul>
<li><em>Cuartiles</em>: son 3 valores (<span class="math inline">\(Q_{1}, Q_{2}, Q_{3}\)</span>) que dividen a la distribución en 4 partes iguales.</li>
<li><em>Quintiles</em>: son 4 valores (<span class="math inline">\(K_{1}, K_{2}, K_{3}, K_{4}\)</span>) que dividen a la distribución en 5 partes iguales.</li>
<li><p><em>Deciles</em>: son 9 valores (<span class="math inline">\(D_1, D_2, D_3, D_4, D_5, D_6, D_7, D_8, D_9\)</span>) que dividen a la distribución en 10 partes iguales.</p></li>
<li><p><em>Percentiles</em>, son 99 valores (<span class="math inline">\(P_1, P_2, \ldots P_{99}\)</span>) que dividen a la distribución en 100 partes iguales.</p></li>
</ul>
</div>
<div id="calculo-de-cuantiles" class="section level3">
<h3><span class="header-section-number">2.5.2</span> Cálculo de cuantiles</h3>
<p>Es fácil darse cuenta que existen equivalencias importantes entre los cuantiles, algunos ejemplos de estas equivalencias:</p>
<ul>
<li><span class="math inline">\(D_5=Q_2=P_{50}\)</span></li>
<li><span class="math inline">\(D_4=K_2=P_{40}\)</span></li>
<li><span class="math inline">\(D_3=P_{30}\)</span></li>
</ul>
<p>Se deduce entonces que no es necesario tener una expresión para cada tipo de cuantiles, basta con conocer una expresión para calcular percentiles. Para esto debemos conocer dos cosas:</p>
<ol style="list-style-type: decimal">
<li>La posición del percentil en nuestro conjunto de datos.</li>
<li>El valor del percentil tomando en cuenta su posición.</li>
</ol>
<p>Para calcular la posición del percentil <span class="math inline">\(i\)</span> que acumula el 100<span class="math inline">\(p\)</span>% en un conjunto de datos no agrupado <span class="math inline">\(X\)</span>, de tamaño <span class="math inline">\(n\)</span> y ordenado en forma ascendente primero determinamos la posición del percentil con la expresión:</p>
<span class="math display" id="eq:posperc">\[\begin{equation} 
  Posición = p(n-1)+1
  \tag{2.6}
\end{equation}\]</span>
<p>Para determinar el valor <span class="math inline">\(X_{i.a}\)</span> utilizamos la expresión:</p>
<span class="math display" id="eq:valperc">\[\begin{equation} 
  X_{i.a}=X_{i}+0.a(X_{i+1}-X_{i})
  \tag{2.7}
\end{equation}\]</span>
<p>Para calcular percentiles en R, se utiliza la función <code>quantile()</code>. Esta función recibe dos argumentos, la variable de la que se calcula el percentil y el porcentaje del percentil que se desea calcular. Se pueden calcular varios percentiles al mismo tiempo.</p>
<p>Vamos a calcular el primer cuartil <span class="math inline">\(Q_{1}\)</span> de la variable <code>ACTIVOS</code> del conjunto de datos ya trabajado anteriormente. Vamos a llamar a esta variable utilizando la notación <code>$</code> esta notación se usa poniendo <code>data.frame$variable</code> en este caso nuestra variable está en el conjunto <code>datos1</code>y se llama <code>ACTIVOS</code> por lo que para llamar la variable desde la función escribimos <code>datos1$ACTIVOS</code>. Luego debemos recordar que <span class="math inline">\(Q_1=P_{25}\)</span> es decir que en la función <code>quantile</code> debemos anotar <span class="math inline">\(0.25\)</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">quantile</span>(big4size<span class="op">$</span>ACTIVOS, <span class="fl">0.25</span>)</code></pre></div>
<pre><code>##     25% 
## 3184669</code></pre>
<p>Ahora calculamos los tres cuartiles en este caso podemos escribir dentro de una lista los tres valores, para ingresar listas en R lo hacemos con <code>c(elemento1, elemento2, ... )</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">quantile</span>(big4size<span class="op">$</span>ACTIVOS, <span class="kw">c</span>(<span class="fl">0.25</span>,<span class="fl">0.50</span>,<span class="fl">0.75</span>))</code></pre></div>
<pre><code>##      25%      50%      75% 
##  3184669 10326361 33192848</code></pre>
<p>De los resultados obtenidos se interpreta que el 25% de los activos de las empresas es menor que <span class="math inline">\(3 184 669\)</span>. Supongamos que se quieren determinar los deciles, una forma de hacer la lista es con la función <code>seq</code> con las instrucciones <code>seq(inicial, final, by = aumento)</code> de esta manera nos evitamos escribir los nueve valores.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">quantile</span>(big4size<span class="op">$</span>ACTIVOS, <span class="kw">seq</span>(<span class="fl">0.1</span>,<span class="fl">0.9</span>, <span class="dt">by =</span> <span class="fl">0.1</span>))</code></pre></div>
<pre><code>##      10%      20%      30%      40%      50%      60%      70%      80% 
##  1621865  2561491  3882643  6187167 10326361 16883801 26613778 49838668 
##      90% 
## 93545755</code></pre>
</div>
</div>
<div id="medidas-de-dispersion" class="section level2">
<h2><span class="header-section-number">2.6</span> Medidas de dispersión</h2>
</div>
<div id="tablas-de-frecuencia" class="section level2">
<h2><span class="header-section-number">2.7</span> Tablas de frecuencia</h2>
<p>Una tabla de frecuencia es una forma de describir los datos de forma resumida, las tablas de frecuencia pueden construirse para variables cualitativas y para variables cuantitativas.</p>
<div id="variables-cualitativas" class="section level3">
<h3><span class="header-section-number">2.7.1</span> Variables Cualitativas</h3>
<p>Para las variables cualitativas una tabla de frecuencia basicámente tiene tres columnas: “Categoría”, “Frecuencia”, “Porcentaje”. Para aprender a realizar tablas de frecuencia para variables cualitativas, trabajaremos con el conjunto de datos <code>audit_bolsa</code>, Este conjunto de datos tiene información sobre las empresas que cotizan en la Bolsa de Valores de Guayaquil, se elaborará una tabla de frecuencias de las firmas auditoras que han trabajado para estas empresas. La variable en la que se almacena esta información es la variable <code>FIRMA</code>. La tabla de frecuencia se elabora usando el paquete <code>dplyr</code>. El comando <code>mutate( )</code> sirve para crear nuevas columnas, en este caso se crea la columna porcentaje.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">setwd</span>(<span class="st">&quot;C:/Users/onava_000/OneDrive/libro_mc/estadistica&quot;</span>)
audit_bolsa &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;audit_bolsa.csv&quot;</span>,<span class="dt">header=</span><span class="ot">TRUE</span>,<span class="dt">sep=</span><span class="st">&quot;;&quot;</span>,<span class="dt">dec=</span><span class="st">&quot;,&quot;</span>)

tabla_firma &lt;-<span class="st"> </span>audit_bolsa <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(FIRMA) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Frecuencia=</span><span class="kw">n</span>()) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Porcentaje =</span> <span class="kw">round</span>(<span class="dv">100</span><span class="op">*</span>Frecuencia<span class="op">/</span><span class="kw">sum</span>(Frecuencia),<span class="dv">2</span>)
         ) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(Porcentaje))
 <span class="kw">print</span>(tabla_firma)</code></pre></div>
<pre><code>## # A tibble: 15 x 3
##    FIRMA                               Frecuencia Porcentaje
##    &lt;fct&gt;                                    &lt;int&gt;      &lt;dbl&gt;
##  1 DELOITTE                                   103      48.6 
##  2 MOORE STEPHENS                              29      13.7 
##  3 PWC PRICE WATER HOUSE COOPERS               24      11.3 
##  4 HANSEN HOLM &amp; CO. CIA. LTDA.                15       7.08
##  5 KPMG                                        13       6.13
##  6 ERNST &amp; YOUNG                                7       3.3 
##  7 BDO                                          6       2.83
##  8 ALTAMIRANO HIDALGO MARIO ROBERTO             3       1.42
##  9 KRESTON                                      3       1.42
## 10 PKF                                          3       1.42
## 11 BATALLAS &amp; BATALLAS                          2       0.94
## 12 ASE + ASESORANDO MAS                         1       0.47
## 13 CONSULTORES MORAN CEDILLO CIA. LTDA          1       0.47
## 14 HERRERA CHANG 6 ASOCIADOS                    1       0.47
## 15 NGV                                          1       0.47</code></pre>
<table>
<caption>
<span id="tab:tabla2">Tabla 2.2: </span>Tabla de Frecuencia de Firmas Auditoras
</caption>
<thead>
<tr>
<th style="text-align:left;">
FIRMA
</th>
<th style="text-align:right;">
Frecuencia
</th>
<th style="text-align:right;">
Porcentaje
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
DELOITTE
</td>
<td style="text-align:right;">
103
</td>
<td style="text-align:right;">
48.58
</td>
</tr>
<tr>
<td style="text-align:left;">
MOORE STEPHENS
</td>
<td style="text-align:right;">
29
</td>
<td style="text-align:right;">
13.68
</td>
</tr>
<tr>
<td style="text-align:left;">
PWC PRICE WATER HOUSE COOPERS
</td>
<td style="text-align:right;">
24
</td>
<td style="text-align:right;">
11.32
</td>
</tr>
<tr>
<td style="text-align:left;">
HANSEN HOLM &amp; CO. CIA. LTDA.
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
7.08
</td>
</tr>
<tr>
<td style="text-align:left;">
KPMG
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
6.13
</td>
</tr>
<tr>
<td style="text-align:left;">
ERNST &amp; YOUNG
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
3.30
</td>
</tr>
<tr>
<td style="text-align:left;">
BDO
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
2.83
</td>
</tr>
<tr>
<td style="text-align:left;">
ALTAMIRANO HIDALGO MARIO ROBERTO
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1.42
</td>
</tr>
<tr>
<td style="text-align:left;">
KRESTON
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1.42
</td>
</tr>
<tr>
<td style="text-align:left;">
PKF
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1.42
</td>
</tr>
<tr>
<td style="text-align:left;">
BATALLAS &amp; BATALLAS
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0.94
</td>
</tr>
<tr>
<td style="text-align:left;">
ASE + ASESORANDO MAS
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.47
</td>
</tr>
<tr>
<td style="text-align:left;">
CONSULTORES MORAN CEDILLO CIA. LTDA
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.47
</td>
</tr>
<tr>
<td style="text-align:left;">
HERRERA CHANG 6 ASOCIADOS
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.47
</td>
</tr>
<tr>
<td style="text-align:left;">
NGV
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.47
</td>
</tr>
</tbody>
</table>
<p>En la tabla <a href="intro.html#tab:tabla2">2.2</a> se aprecia el resultado obtenido y formateado para ser publicado. El resultado de R, puede ser exportado a un archivo Excel con la finalidad de luego tomar esa tabla y llevarla a un documento donde se presentará toda la información analizada. Para exportar la información a un archivo excel se puede trabajar con el paquete <code>xlsx</code>. Para exportar los resultados a Excel se puede proceder de la siguiente forma.</p>
<ol style="list-style-type: decimal">
<li>Cargar el paquete <code>xlsx</code>.</li>
<li>Convertir el resultado a un <code>data frame</code> utilizando la función <code>as.data.frame()</code></li>
<li>Exportar el resultado con la función <code>write.xlsx()</code> cuya estructura básica es <code>write.xlsx(datos, &quot;archivo.xlsx&quot;)</code>, si se desea consultar más detalles de la función se puede escribir <code>?write.xlsx</code>.</li>
</ol>
<p>El resultado de esta operación será un archivo de excel guardado en nuestro directorio de trabajo.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(xlsx)
tabla_firma =<span class="st"> </span><span class="kw">as.data.frame</span>(tabla_firma)
<span class="kw">write.xlsx</span>(tabla_firma, <span class="st">&quot;tablas.xlsx&quot;</span>, <span class="dt">sheetName =</span> <span class="st">&quot;firmas&quot;</span>, <span class="dt">row.names =</span> <span class="ot">FALSE</span>)</code></pre></div>
<p>La opción <code>sheetname = &quot;firmas&quot;</code> crea dentro del libro <code>tablas.xlsx</code> una hoja de cálculo llamada <code>firmas</code>. La opción <code>row.names = FALSE</code> hace que en el archivo final no se graben los números de cada fila.</p>
<p>Nota: es importante tener fijado el directorio de trabajo, como se explicó en la sección <a href="intro.html#primerR">2.3</a>.</p>
</div>
<div id="variables-cuantitativas" class="section level3">
<h3><span class="header-section-number">2.7.2</span> Variables Cuantitativas</h3>
<p>Una tabla de frecuencias para variables cualitativas tiene 6 columnas:</p>
<ol style="list-style-type: decimal">
<li>Clase: una clase es un intervalo del tipo <span class="math inline">\(\left[ menor, mayor \right)\)</span></li>
<li>Marca de Clase: es un valor igual al promedio de los dos extremos de la clase.</li>
<li>Frecuencia: la frecuencia es igual al número de valores de la variable que están dentro del intervalo.</li>
<li>Frecuencia relativa: la frecuencia relativa se la calcula como la frecuencia dividida para el total de valores de la variable.</li>
<li>Frecuencia acumulada: se la calcula sumando las frecuencias desde la primera clase hasta la clase en consideración.</li>
<li>Frecuencia Relativa acumulada: se la calcula como la frecuencia acumulada pero para las frecuencias relativas.</li>
</ol>
<p>Una de las ventajas de usar R es que se pueden crear funciones para cada necesidad que el investigador tenga, en este caso el código que se muestra sirve para hacer tablas de frecuencia de cualquier variable cuantitativa. A manera de ejemplo se hará la tabla de frecuencia de la variable <code>VTAS</code> en millones de dólares, del conjunto de datos trabajado en la sección <a href="intro.html#primerR">2.3</a>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(agricolae)
<span class="kw">library</span>(dplyr)

h2&lt;-<span class="kw">with</span>(big4size,<span class="kw">graph.freq</span>(VTAS<span class="op">/</span><span class="dv">1000000</span>,<span class="dt">plot=</span><span class="ot">FALSE</span>));

h2 =<span class="st"> </span><span class="kw">table.freq</span>(h2)

h3 &lt;-<span class="st"> </span>h2 <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Clase =</span> <span class="kw">paste</span>(<span class="st">&quot;[&quot;</span>,Lower,<span class="st">&quot;,&quot;</span>,Upper,<span class="st">&quot;)&quot;</span>),    
        <span class="st">&quot;Marca de Clase&quot;</span>  =<span class="st">  </span>Main,
        <span class="dt">Frec. =</span> Frequency,
        <span class="st">&quot;Frec. Rel.&quot;</span> =<span class="st"> </span>Percentage,
        <span class="st">&quot;Frec. Acu.&quot;</span> =<span class="st"> </span>CF,
        <span class="st">&quot;Rel. Acu.&quot;</span> =<span class="st"> </span>CPF )  <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(<span class="op">-</span><span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">7</span>))</code></pre></div>
<table>
<caption>
<span id="tab:tabla3">Tabla 2.3: </span>Tabla de Frecuencia de las Ventas
</caption>
<thead>
<tr>
<th style="text-align:left;">
Clase
</th>
<th style="text-align:right;">
Marca de Clase
</th>
<th style="text-align:right;">
Frec.
</th>
<th style="text-align:right;">
Frec. Rel.
</th>
<th style="text-align:right;">
Frec. Acu.
</th>
<th style="text-align:right;">
Rel. Acu.
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
[ 0 , 165.76 )
</td>
<td style="text-align:right;">
82.88
</td>
<td style="text-align:right;">
2099
</td>
<td style="text-align:right;">
93.0
</td>
<td style="text-align:right;">
2099
</td>
<td style="text-align:right;">
93.0
</td>
</tr>
<tr>
<td style="text-align:left;">
[ 165.76 , 331.52 )
</td>
<td style="text-align:right;">
248.64
</td>
<td style="text-align:right;">
83
</td>
<td style="text-align:right;">
3.7
</td>
<td style="text-align:right;">
2182
</td>
<td style="text-align:right;">
96.7
</td>
</tr>
<tr>
<td style="text-align:left;">
[ 331.52 , 497.28 )
</td>
<td style="text-align:right;">
414.40
</td>
<td style="text-align:right;">
35
</td>
<td style="text-align:right;">
1.6
</td>
<td style="text-align:right;">
2217
</td>
<td style="text-align:right;">
98.3
</td>
</tr>
<tr>
<td style="text-align:left;">
[ 497.28 , 663.04 )
</td>
<td style="text-align:right;">
580.16
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
0.8
</td>
<td style="text-align:right;">
2234
</td>
<td style="text-align:right;">
99.0
</td>
</tr>
<tr>
<td style="text-align:left;">
[ 663.04 , 828.8 )
</td>
<td style="text-align:right;">
745.92
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.0
</td>
<td style="text-align:right;">
2234
</td>
<td style="text-align:right;">
99.0
</td>
</tr>
<tr>
<td style="text-align:left;">
[ 828.8 , 994.56 )
</td>
<td style="text-align:right;">
911.68
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
0.3
</td>
<td style="text-align:right;">
2241
</td>
<td style="text-align:right;">
99.3
</td>
</tr>
<tr>
<td style="text-align:left;">
[ 994.56 , 1160.32 )
</td>
<td style="text-align:right;">
1077.44
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
0.5
</td>
<td style="text-align:right;">
2253
</td>
<td style="text-align:right;">
99.9
</td>
</tr>
<tr>
<td style="text-align:left;">
[ 1160.32 , 1326.08 )
</td>
<td style="text-align:right;">
1243.20
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.0
</td>
<td style="text-align:right;">
2253
</td>
<td style="text-align:right;">
99.9
</td>
</tr>
<tr>
<td style="text-align:left;">
[ 1326.08 , 1491.84 )
</td>
<td style="text-align:right;">
1408.96
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.0
</td>
<td style="text-align:right;">
2253
</td>
<td style="text-align:right;">
99.9
</td>
</tr>
<tr>
<td style="text-align:left;">
[ 1491.84 , 1657.6 )
</td>
<td style="text-align:right;">
1574.72
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.0
</td>
<td style="text-align:right;">
2253
</td>
<td style="text-align:right;">
99.9
</td>
</tr>
<tr>
<td style="text-align:left;">
[ 1657.6 , 1823.36 )
</td>
<td style="text-align:right;">
1740.48
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0.1
</td>
<td style="text-align:right;">
2255
</td>
<td style="text-align:right;">
100.0
</td>
</tr>
<tr>
<td style="text-align:left;">
[ 1823.36 , 1989.12 )
</td>
<td style="text-align:right;">
1906.24
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.0
</td>
<td style="text-align:right;">
2256
</td>
<td style="text-align:right;">
100.0
</td>
</tr>
</tbody>
</table>
<p>De la tabla <a href="intro.html#tab:tabla3">2.3</a> se obsserva que el <span class="math inline">\(93\%\)</span> de las empresas realiza ventas entre 0 y <span class="math inline">\(165.76\)</span> millones. El <span class="math inline">\(99\%\)</span> de las empresas es decir <span class="math inline">\(2234\)</span> tiene ventas menores a <span class="math inline">\(663.04\)</span> millones de dólares, esto se lo puede ver en la columna de frecuencias acumuladas relativas. Además, solo una empresa tiene ventas entre <span class="math inline">\(1823.36\)</span> y <span class="math inline">\(1989.12\)</span> millones. Finalmente vamos a exportar la tabla de frecuencia en el archivo <code>tablas.xlsx</code>. La opción <code>append = TRUE</code> sirve para añadir una nueva hoja de cálculo al libro.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(xlsx)
h3 =<span class="st"> </span><span class="kw">as.data.frame</span>(h3)
<span class="kw">write.xlsx</span>(h3, <span class="st">&quot;tablas.xlsx&quot;</span>, <span class="dt">sheetName =</span> <span class="st">&quot;frec_ventas&quot;</span>, <span class="dt">row.names =</span> <span class="ot">FALSE</span>,<span class="dt">append=</span><span class="ot">TRUE</span>)</code></pre></div>
</div>
</div>
<div id="tablas-de-contingencia" class="section level2">
<h2><span class="header-section-number">2.8</span> Tablas de Contingencia</h2>
<p>Una tabla de contingencia es una forma útil para examinar relaciones entre dos variables categóricas. Los valores en las celdas de una tabla de contingencia pueden ser de frecuencia absoluta o frecuencia relativa.</p>
<p>Para ejemplificar la construcción de una tabla de contingencia vamos a trabajar con el archivo <code>Ranking2018Guayas.csv</code> este archivo contiene información sobre una muestra de 162 empresas de la provincia del Guayas. Se analizará la relación entre la ciudad y el tamaño de las empresas.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">setwd</span>(<span class="st">&quot;C:/Users/onava_000/OneDrive/libro_mc/estadistica&quot;</span>)
rank2018 =<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;Ranking2018Guayas.csv&quot;</span>,<span class="dt">header=</span><span class="ot">TRUE</span>, <span class="dt">sep=</span><span class="st">&quot;;&quot;</span>)


ciudad.tama =<span class="st"> </span>rank2018 <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(CIUDAD, TAMAÑO)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">n=</span><span class="kw">n</span>())<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">spread</span>(TAMAÑO, n) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">replace</span>(., <span class="kw">is.na</span>(.), <span class="dv">0</span>)</code></pre></div>
<table>
<caption>
<span id="tab:tabla4">Tabla 2.4: </span>Tabla de Contingencia de las empresas clasificadas por tamaño y ciudad
</caption>
<thead>
<tr>
<th style="text-align:left;">
CIUDAD
</th>
<th style="text-align:right;">
MEDIANA
</th>
<th style="text-align:right;">
MICROEMPRESA
</th>
<th style="text-align:right;">
PEQUEÑA
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
DAULE
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
ELOY ALFARO
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
GUAYAQUIL
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
117
</td>
<td style="text-align:right;">
28
</td>
</tr>
<tr>
<td style="text-align:left;">
MILAGRO
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
NARANJITO
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
SAMBORONDÓN
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
SANTA LUCIA
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
VELASCO IBARRA
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
</tr>
</tbody>
</table>
<p>En la tabla <a href="intro.html#tab:tabla4">2.4</a> se observa que de las 162 empresas 117 son microempresas y de la ciudad de Guayaquil, de la ciudad de Samborondón se ha tomada una empresa pequeña. Esta información, como se mencionó antes, puede también ser mostrada en porcentajes. En la tabla <a href="intro.html#tab:tabla5">2.5</a> se observa la tabla de contingencia con los porcentajes.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ciudad.tama.porc =<span class="st"> </span>rank2018 <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(CIUDAD, TAMAÑO)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Porc =</span> <span class="kw">round</span>(<span class="dv">100</span><span class="op">*</span><span class="kw">n</span>()<span class="op">/</span><span class="kw">nrow</span>(rank2018),<span class="dv">2</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">spread</span>(TAMAÑO, Porc) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">replace</span>(., <span class="kw">is.na</span>(.), <span class="dv">0</span>)</code></pre></div>
<table>
<caption>
<span id="tab:tabla5">Tabla 2.5: </span>Tabla de Contingencia de las empresas clasificadas por tamaño y ciudad
</caption>
<thead>
<tr>
<th style="text-align:left;">
CIUDAD
</th>
<th style="text-align:right;">
MEDIANA
</th>
<th style="text-align:right;">
MICROEMPRESA
</th>
<th style="text-align:right;">
PEQUEÑA
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
DAULE
</td>
<td style="text-align:right;">
0.62
</td>
<td style="text-align:right;">
0.62
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
<tr>
<td style="text-align:left;">
ELOY ALFARO
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
1.24
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
<tr>
<td style="text-align:left;">
GUAYAQUIL
</td>
<td style="text-align:right;">
1.24
</td>
<td style="text-align:right;">
72.67
</td>
<td style="text-align:right;">
17.39
</td>
</tr>
<tr>
<td style="text-align:left;">
MILAGRO
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
1.24
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
<tr>
<td style="text-align:left;">
NARANJITO
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
2.48
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
<tr>
<td style="text-align:left;">
SAMBORONDÓN
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
0.62
</td>
</tr>
<tr>
<td style="text-align:left;">
SANTA LUCIA
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
0.62
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
<tr>
<td style="text-align:left;">
VELASCO IBARRA
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
0.62
</td>
<td style="text-align:right;">
0.62
</td>
</tr>
</tbody>
</table>
</div>
<div id="graficos-y-visualizacion" class="section level2">
<h2><span class="header-section-number">2.9</span> Gráficos y Visualización</h2>
<p>Para realizar gráficas R tiene algunos paquetes disponibles, sin embargo en este texto trabajaremos con el paquete <code>ggplot2</code>. Este paquete está basada en la gramática de los gráficos <span class="citation">(Wilkinson <a href="#ref-wilkinson2005">2005</a>)</span>.</p>
<div id="histogramas" class="section level3">
<h3><span class="header-section-number">2.9.1</span> Histogramas</h3>
<p>Los histogramas se utilizan para variables continuas. Un histograma es un gráfico de la distribución de frecuencia de una variable, en el eje vertical se representa la frecuencia (absoluta o relativa) y en el eje horizontal los rangos de los valores.</p>
<p>En la figura <a href="intro.html#fig:figura1">2.3</a> se muestra el histograma de la variable ventas en millones de dólares del archivo <em>cap2_big4_size.csv</em> ya descrito en la sección <a href="intro.html#primerR">2.3</a>, este primer histograma ha sido configurado para presentar 12 barras, que las barras sean de color azul con un contorno rojo. Antes de abordar los detalles mencionados discutiremos brevemente el funcionamiento de la gramática de <code>ggplot2</code>, una gráfica realizada en <code>ggplot2</code> empieza por <code>ggplot(data, aes())</code> dentro de <code>aes()</code> se indica las variables que van a intervenir en la gráfica, Luego se añade la <code>geom</code> con la que se va a trabajar en este caso se escogió <code>geom_histogram()</code> puesto que se desea realizar un histograma. Como se indicó anteriormente se configuró el histograma con 12 barras (<code>bins=12</code>), la opción <code>color=&quot;red&quot;</code> permite que el contorno de las barrras sea rojo y la opción <code>fill=&quot;blue&quot;</code>hace que las barras sean de color azul.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)

<span class="kw">ggplot</span>(big4size, <span class="kw">aes</span>(<span class="dt">x=</span> VTAS<span class="op">/</span><span class="dv">1000000</span>)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins=</span><span class="dv">12</span>, <span class="dt">color=</span> <span class="st">&quot;red&quot;</span>, <span class="dt">fill=</span><span class="st">&quot;blue&quot;</span> )</code></pre></div>
<div class="figure"><span id="fig:figura1"></span>
<img src="estadistica_files/figure-html/figura1-1.png" alt="Histograma de las Ventas" width="672" />
<p class="caption">
Figura 2.3: Histograma de las Ventas
</p>
</div>
<p>Para configurar las etiquetas de los ejes podemos añadir las opciones <code>xlab( )</code> y <code>ylab( )</code>. En la figura <a href="intro.html#fig:figura2">2.4</a> se aprecia el histograma con las etiquetas de los ejes añadidos.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)

<span class="kw">ggplot</span>(big4size, <span class="kw">aes</span>(<span class="dt">x=</span> VTAS<span class="op">/</span><span class="dv">1000000</span>)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins=</span><span class="dv">12</span>, <span class="dt">color=</span> <span class="st">&quot;red&quot;</span>,  <span class="dt">fill=</span><span class="st">&quot;blue&quot;</span> ) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Ventas en Millones de Dólares&quot;) + ylab(&quot;</span>Frecuencia<span class="st">&quot;)</span></code></pre></div>
<div class="figure"><span id="fig:figura2"></span>
<img src="estadistica_files/figure-html/figura2-1.png" alt="Histograma de las Ventas con Etiquetas en los Ejes" width="672" />
<p class="caption">
Figura 2.4: Histograma de las Ventas con Etiquetas en los Ejes
</p>
</div>
<p>Usando el archivo <code>Ranking2018Guayas.csv</code>, vamos ahora a hacer el histograma de las ventas de acuerdo al tamaño de la empresa. En la figura <a href="intro.html#fig:figura3">2.5</a> se observa el histograma.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(rank2018, <span class="kw">aes</span>(<span class="dt">x=</span>VENTAS<span class="op">/</span><span class="dv">1000</span>, <span class="dt">fill=</span>TAMAÑO)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">alpha=</span><span class="fl">0.3</span>, <span class="dt">color=</span><span class="st">&quot;black&quot;</span>,<span class="dt">bins=</span><span class="dv">9</span>, <span class="dt">binwidth =</span> <span class="dv">150</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="dv">0</span>,<span class="dv">1350</span>,<span class="dv">150</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">90</span>, <span class="dt">hjust =</span> <span class="dv">1</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Ventas en Miles&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Frecuencia&quot;</span>)</code></pre></div>
<div class="figure"><span id="fig:figura3"></span>
<img src="estadistica_files/figure-html/figura3-1.png" alt="Histograma de las Ventas de Acuerdo al Tamaño de la empresa" width="672" />
<p class="caption">
Figura 2.5: Histograma de las Ventas de Acuerdo al Tamaño de la empresa
</p>
</div>
</div>
<div id="diagramas-de-caja-y-valores-atipicos" class="section level3">
<h3><span class="header-section-number">2.9.2</span> Diagramas de Caja y valores atípicos</h3>
<div id="intervalos-de-confianza" class="section level4">
<h4><span class="header-section-number">2.9.2.1</span> Intervalos de Confianza</h4>

</div>
</div>
</div>
</div>
<h3>Bibliografía</h3>
<div id="refs" class="references">
<div id="ref-wilkinson2005">
<p>Wilkinson, Leland. 2005. <em>The Grammar of Graphics</em>. 2nd ed. New York: Springer-Verlag. <a href="https://www.springer.com/us/book/9780387245447" class="uri">https://www.springer.com/us/book/9780387245447</a>.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="pruebas-de-hipotesis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["estadistica.pdf", "estadistica.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
