<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>2.8 Tablas de frecuencia | Análisis Estadístico de Datos Financieros con R</title>
  <meta name="description" content="Libro de Análisis Estadístico de Datos Financieros con R">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="2.8 Tablas de frecuencia | Análisis Estadístico de Datos Financieros con R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Libro de Análisis Estadístico de Datos Financieros con R" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2.8 Tablas de frecuencia | Análisis Estadístico de Datos Financieros con R" />
  
  <meta name="twitter:description" content="Libro de Análisis Estadístico de Datos Financieros con R" />
  

<meta name="author" content="Oswaldo Navarrete Carreño, María Alexandra Chávez">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="medidas-de-dispersion.html">
<link rel="next" href="tablas-de-contingencia.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Análisis Estadístico de Datos Financieros Con R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> ¿A quién va dirigido este libro?</a><ul>
<li class="chapter" data-level="1.1" data-path="instalando-r-y-rstudio.html"><a href="instalando-r-y-rstudio.html"><i class="fa fa-check"></i><b>1.1</b> Instalando R Y Rstudio</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introducción</a><ul>
<li class="chapter" data-level="2.1" data-path="estadistica-descriptiva-e-inferencial.html"><a href="estadistica-descriptiva-e-inferencial.html"><i class="fa fa-check"></i><b>2.1</b> Estadística descriptiva e inferencial</a></li>
<li class="chapter" data-level="2.2" data-path="tipos-de-variables.html"><a href="tipos-de-variables.html"><i class="fa fa-check"></i><b>2.2</b> Tipos de Variables</a><ul>
<li class="chapter" data-level="2.2.1" data-path="tipos-de-variables.html"><a href="tipos-de-variables.html#niveles-de-medicion"><i class="fa fa-check"></i><b>2.2.1</b> Niveles de medición</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="otros-conceptos-importantes.html"><a href="otros-conceptos-importantes.html"><i class="fa fa-check"></i><b>2.3</b> Otros conceptos importantes</a></li>
<li class="chapter" data-level="2.4" data-path="primerR.html"><a href="primerR.html"><i class="fa fa-check"></i><b>2.4</b> Primeros pasos en R</a></li>
<li class="chapter" data-level="2.5" data-path="medidas-de-tendencia-central.html"><a href="medidas-de-tendencia-central.html"><i class="fa fa-check"></i><b>2.5</b> Medidas de Tendencia Central</a><ul>
<li class="chapter" data-level="2.5.1" data-path="medidas-de-tendencia-central.html"><a href="medidas-de-tendencia-central.html#media"><i class="fa fa-check"></i><b>2.5.1</b> Media</a></li>
<li class="chapter" data-level="2.5.2" data-path="medidas-de-tendencia-central.html"><a href="medidas-de-tendencia-central.html#mediana"><i class="fa fa-check"></i><b>2.5.2</b> Mediana</a></li>
<li class="chapter" data-level="2.5.3" data-path="medidas-de-tendencia-central.html"><a href="medidas-de-tendencia-central.html#moda"><i class="fa fa-check"></i><b>2.5.3</b> Moda</a></li>
<li class="chapter" data-level="2.5.4" data-path="medidas-de-tendencia-central.html"><a href="medidas-de-tendencia-central.html#trabajamos-con-la-media-o-la-mediana"><i class="fa fa-check"></i><b>2.5.4</b> ¿trabajamos con la media o la mediana?</a></li>
<li class="chapter" data-level="2.5.5" data-path="medidas-de-tendencia-central.html"><a href="medidas-de-tendencia-central.html#calculo-de-las-medidas-de-tendencia-central-en-r"><i class="fa fa-check"></i><b>2.5.5</b> Cálculo de las medidas de tendencia central en R</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="medidas-de-posicion-cuantiles.html"><a href="medidas-de-posicion-cuantiles.html"><i class="fa fa-check"></i><b>2.6</b> Medidas de posición (Cuantiles)</a><ul>
<li class="chapter" data-level="2.6.1" data-path="medidas-de-posicion-cuantiles.html"><a href="medidas-de-posicion-cuantiles.html#tipos-de-cuantiles"><i class="fa fa-check"></i><b>2.6.1</b> Tipos de Cuantiles</a></li>
<li class="chapter" data-level="2.6.2" data-path="medidas-de-posicion-cuantiles.html"><a href="medidas-de-posicion-cuantiles.html#calculo-de-cuantiles"><i class="fa fa-check"></i><b>2.6.2</b> Cálculo de cuantiles</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="medidas-de-dispersion.html"><a href="medidas-de-dispersion.html"><i class="fa fa-check"></i><b>2.7</b> Medidas de dispersión</a><ul>
<li class="chapter" data-level="2.7.1" data-path="medidas-de-dispersion.html"><a href="medidas-de-dispersion.html#rango"><i class="fa fa-check"></i><b>2.7.1</b> Rango</a></li>
<li class="chapter" data-level="2.7.2" data-path="medidas-de-dispersion.html"><a href="medidas-de-dispersion.html#varianza"><i class="fa fa-check"></i><b>2.7.2</b> Varianza</a></li>
<li class="chapter" data-level="2.7.3" data-path="medidas-de-dispersion.html"><a href="medidas-de-dispersion.html#desviacion"><i class="fa fa-check"></i><b>2.7.3</b> Desviación</a></li>
<li class="chapter" data-level="2.7.4" data-path="medidas-de-dispersion.html"><a href="medidas-de-dispersion.html#medidas-de-dispersion-en-r"><i class="fa fa-check"></i><b>2.7.4</b> Medidas de dispersión en R</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="tablas-de-frecuencia.html"><a href="tablas-de-frecuencia.html"><i class="fa fa-check"></i><b>2.8</b> Tablas de frecuencia</a><ul>
<li class="chapter" data-level="2.8.1" data-path="tablas-de-frecuencia.html"><a href="tablas-de-frecuencia.html#variables-cualitativas"><i class="fa fa-check"></i><b>2.8.1</b> Variables Cualitativas</a></li>
<li class="chapter" data-level="2.8.2" data-path="tablas-de-frecuencia.html"><a href="tablas-de-frecuencia.html#variables-cuantitativas"><i class="fa fa-check"></i><b>2.8.2</b> Variables Cuantitativas</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="tablas-de-contingencia.html"><a href="tablas-de-contingencia.html"><i class="fa fa-check"></i><b>2.9</b> Tablas de Contingencia</a></li>
<li class="chapter" data-level="2.10" data-path="graficos-y-visualizacion.html"><a href="graficos-y-visualizacion.html"><i class="fa fa-check"></i><b>2.10</b> Gráficos y Visualización</a><ul>
<li class="chapter" data-level="2.10.1" data-path="graficos-y-visualizacion.html"><a href="graficos-y-visualizacion.html#histogramas"><i class="fa fa-check"></i><b>2.10.1</b> Histogramas</a></li>
<li class="chapter" data-level="2.10.2" data-path="graficos-y-visualizacion.html"><a href="graficos-y-visualizacion.html#boxes"><i class="fa fa-check"></i><b>2.10.2</b> Diagramas de Caja y valores atípicos</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="intervalos-de-confianza-y-pruebas-de-hipotesis.html"><a href="intervalos-de-confianza-y-pruebas-de-hipotesis.html"><i class="fa fa-check"></i><b>3</b> Intervalos de Confianza y Pruebas de Hipótesis</a><ul>
<li class="chapter" data-level="3.1" data-path="ic.html"><a href="ic.html"><i class="fa fa-check"></i><b>3.1</b> Intervalos de Confianza</a><ul>
<li class="chapter" data-level="3.1.1" data-path="ic.html"><a href="ic.html#intervalo-de-confianza-para-la-media"><i class="fa fa-check"></i><b>3.1.1</b> Intervalo de Confianza para la media</a></li>
<li class="chapter" data-level="3.1.2" data-path="ic.html"><a href="ic.html#intervalo-de-confianza-para-la-proporcion"><i class="fa fa-check"></i><b>3.1.2</b> Intervalo de Confianza para la proporción</a></li>
<li class="chapter" data-level="3.1.3" data-path="ic.html"><a href="ic.html#intervalo-de-confianza-para-la-diferencia-de-medias"><i class="fa fa-check"></i><b>3.1.3</b> Intervalo de Confianza para la diferencia de medias</a></li>
<li class="chapter" data-level="3.1.4" data-path="ic.html"><a href="ic.html#intervalo-de-confianza-para-la-diferencia-de-proporciones"><i class="fa fa-check"></i><b>3.1.4</b> Intervalo de Confianza para la diferencia de proporciones</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="ph.html"><a href="ph.html"><i class="fa fa-check"></i><b>3.2</b> Pruebas de hipótesis</a><ul>
<li class="chapter" data-level="3.2.1" data-path="ph.html"><a href="ph.html#pruebas-de-hipotesis-para-la-media"><i class="fa fa-check"></i><b>3.2.1</b> Pruebas de hipótesis para la media</a></li>
<li class="chapter" data-level="3.2.2" data-path="ph.html"><a href="ph.html#pruebas-de-hipotesis-para-la-proporcion"><i class="fa fa-check"></i><b>3.2.2</b> Pruebas de hipótesis para la proporción</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="methods.html"><a href="methods.html"><i class="fa fa-check"></i><b>4</b> Regresión</a></li>
<li class="chapter" data-level="5" data-path="analisis-factorial.html"><a href="analisis-factorial.html"><i class="fa fa-check"></i><b>5</b> Análisis Factorial</a><ul>
<li class="chapter" data-level="5.1" data-path="analisis-de-fiabilidad.html"><a href="analisis-de-fiabilidad.html"><i class="fa fa-check"></i><b>5.1</b> Análisis de Fiabilidad</a></li>
<li class="chapter" data-level="5.2" data-path="evaluacion-de-analisis-factorial.html"><a href="evaluacion-de-analisis-factorial.html"><i class="fa fa-check"></i><b>5.2</b> Evaluación de Análisis Factorial</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="algo-de-series-de-tiempo.html"><a href="algo-de-series-de-tiempo.html"><i class="fa fa-check"></i><b>6</b> Algo de series de tiempo</a></li>
<li class="chapter" data-level="" data-path="bibliografia.html"><a href="bibliografia.html"><i class="fa fa-check"></i>Bibliografía</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Análisis Estadístico de Datos Financieros con R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="tablas-de-frecuencia" class="section level2">
<h2><span class="header-section-number">2.8</span> Tablas de frecuencia</h2>
<p>Una tabla de frecuencia es una forma de describir los datos de forma resumida, las tablas de frecuencia pueden construirse para variables cualitativas y para variables cuantitativas.</p>
<div id="variables-cualitativas" class="section level3">
<h3><span class="header-section-number">2.8.1</span> Variables Cualitativas</h3>
<p>Para las variables cualitativas una tabla de frecuencia basicámente tiene tres columnas: “Categoría”, “Frecuencia”, “Porcentaje”. Para aprender a realizar tablas de frecuencia para variables cualitativas, trabajaremos con el conjunto de datos <code>audit_bolsa</code>, Este conjunto de datos tiene información sobre las empresas que cotizan en la Bolsa de Valores de Guayaquil, se elaborará una tabla de frecuencias de las firmas auditoras que han trabajado para estas empresas. La variable en la que se almacena esta información es la variable <code>FIRMA</code>. La tabla de frecuencia se elabora usando el paquete <code>dplyr</code>. El comando <code>mutate( )</code> sirve para crear nuevas columnas, en este caso se crea la columna porcentaje.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">setwd</span>(<span class="st">&quot;C:/Users/onava_000/OneDrive/libro_mc/estadistica&quot;</span>)
audit_bolsa &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;audit_bolsa.csv&quot;</span>,<span class="dt">header=</span><span class="ot">TRUE</span>,<span class="dt">sep=</span><span class="st">&quot;;&quot;</span>,<span class="dt">dec=</span><span class="st">&quot;,&quot;</span>)

tabla_firma &lt;-<span class="st"> </span>audit_bolsa <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(FIRMA) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Frecuencia=</span><span class="kw">n</span>()) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Porcentaje =</span> <span class="kw">round</span>(<span class="dv">100</span><span class="op">*</span>Frecuencia<span class="op">/</span><span class="kw">sum</span>(Frecuencia),<span class="dv">2</span>)
         ) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(Porcentaje))
 <span class="kw">print</span>(tabla_firma)</code></pre></div>
<pre><code>## # A tibble: 15 x 3
##    FIRMA                               Frecuencia Porcentaje
##    &lt;fct&gt;                                    &lt;int&gt;      &lt;dbl&gt;
##  1 DELOITTE                                   103      48.6 
##  2 MOORE STEPHENS                              29      13.7 
##  3 PWC PRICE WATER HOUSE COOPERS               24      11.3 
##  4 HANSEN HOLM &amp; CO. CIA. LTDA.                15       7.08
##  5 KPMG                                        13       6.13
##  6 ERNST &amp; YOUNG                                7       3.3 
##  7 BDO                                          6       2.83
##  8 ALTAMIRANO HIDALGO MARIO ROBERTO             3       1.42
##  9 KRESTON                                      3       1.42
## 10 PKF                                          3       1.42
## 11 BATALLAS &amp; BATALLAS                          2       0.94
## 12 ASE + ASESORANDO MAS                         1       0.47
## 13 CONSULTORES MORAN CEDILLO CIA. LTDA          1       0.47
## 14 HERRERA CHANG 6 ASOCIADOS                    1       0.47
## 15 NGV                                          1       0.47</code></pre>
<table>
<caption>
<span id="tab:tabla2">Tabla 2.2: </span>Tabla de Frecuencia de Firmas Auditoras
</caption>
<thead>
<tr>
<th style="text-align:left;">
FIRMA
</th>
<th style="text-align:right;">
Frecuencia
</th>
<th style="text-align:right;">
Porcentaje
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
DELOITTE
</td>
<td style="text-align:right;">
103
</td>
<td style="text-align:right;">
48.58
</td>
</tr>
<tr>
<td style="text-align:left;">
MOORE STEPHENS
</td>
<td style="text-align:right;">
29
</td>
<td style="text-align:right;">
13.68
</td>
</tr>
<tr>
<td style="text-align:left;">
PWC PRICE WATER HOUSE COOPERS
</td>
<td style="text-align:right;">
24
</td>
<td style="text-align:right;">
11.32
</td>
</tr>
<tr>
<td style="text-align:left;">
HANSEN HOLM &amp; CO. CIA. LTDA.
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
7.08
</td>
</tr>
<tr>
<td style="text-align:left;">
KPMG
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
6.13
</td>
</tr>
<tr>
<td style="text-align:left;">
ERNST &amp; YOUNG
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
3.30
</td>
</tr>
<tr>
<td style="text-align:left;">
BDO
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
2.83
</td>
</tr>
<tr>
<td style="text-align:left;">
ALTAMIRANO HIDALGO MARIO ROBERTO
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1.42
</td>
</tr>
<tr>
<td style="text-align:left;">
KRESTON
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1.42
</td>
</tr>
<tr>
<td style="text-align:left;">
PKF
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1.42
</td>
</tr>
<tr>
<td style="text-align:left;">
BATALLAS &amp; BATALLAS
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0.94
</td>
</tr>
<tr>
<td style="text-align:left;">
ASE + ASESORANDO MAS
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.47
</td>
</tr>
<tr>
<td style="text-align:left;">
CONSULTORES MORAN CEDILLO CIA. LTDA
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.47
</td>
</tr>
<tr>
<td style="text-align:left;">
HERRERA CHANG 6 ASOCIADOS
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.47
</td>
</tr>
<tr>
<td style="text-align:left;">
NGV
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.47
</td>
</tr>
</tbody>
</table>
<p>En la tabla <a href="tablas-de-frecuencia.html#tab:tabla2">2.2</a> se aprecia el resultado obtenido y formateado para ser publicado. El resultado de R, puede ser exportado a un archivo Excel con la finalidad de luego tomar esa tabla y llevarla a un documento donde se presentará toda la información analizada. Para exportar la información a un archivo excel se puede trabajar con el paquete <code>xlsx</code>. Para exportar los resultados a Excel se puede proceder de la siguiente forma.</p>
<ol style="list-style-type: decimal">
<li>Cargar el paquete <code>xlsx</code>.</li>
<li>Convertir el resultado a un <code>data frame</code> utilizando la función <code>as.data.frame()</code></li>
<li>Exportar el resultado con la función <code>write.xlsx()</code> cuya estructura básica es <code>write.xlsx(datos, &quot;archivo.xlsx&quot;)</code>, si se desea consultar más detalles de la función se puede escribir <code>?write.xlsx</code>.</li>
</ol>
<p>El resultado de esta operación será un archivo de excel guardado en nuestro directorio de trabajo.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(xlsx)
tabla_firma =<span class="st"> </span><span class="kw">as.data.frame</span>(tabla_firma)
<span class="kw">write.xlsx</span>(tabla_firma, <span class="st">&quot;tablas.xlsx&quot;</span>, <span class="dt">sheetName =</span> <span class="st">&quot;firmas&quot;</span>, <span class="dt">row.names =</span> <span class="ot">FALSE</span>)</code></pre></div>
<p>La opción <code>sheetname = &quot;firmas&quot;</code> crea dentro del libro <code>tablas.xlsx</code> una hoja de cálculo llamada <code>firmas</code>. La opción <code>row.names = FALSE</code> hace que en el archivo final no se graben los números de cada fila.</p>
<p>Nota: es importante tener fijado el directorio de trabajo, como se explicó en la sección <a href="primerR.html#primerR">2.4</a>.</p>
</div>
<div id="variables-cuantitativas" class="section level3">
<h3><span class="header-section-number">2.8.2</span> Variables Cuantitativas</h3>
<p>Una tabla de frecuencias para variables cualitativas tiene 6 columnas:</p>
<ol style="list-style-type: decimal">
<li>Clase: una clase es un intervalo del tipo <span class="math inline">\(\left[ menor, mayor \right)\)</span></li>
<li>Marca de Clase: es un valor igual al promedio de los dos extremos de la clase.</li>
<li>Frecuencia: la frecuencia es igual al número de valores de la variable que están dentro del intervalo.</li>
<li>Frecuencia relativa: la frecuencia relativa se la calcula como la frecuencia dividida para el total de valores de la variable.</li>
<li>Frecuencia acumulada: se la calcula sumando las frecuencias desde la primera clase hasta la clase en consideración.</li>
<li>Frecuencia Relativa acumulada: se la calcula como la frecuencia acumulada pero para las frecuencias relativas.</li>
</ol>
<p>Una de las ventajas de usar R es que se pueden crear funciones para cada necesidad que el investigador tenga, en este caso el código que se muestra sirve para hacer tablas de frecuencia de cualquier variable cuantitativa. A manera de ejemplo se hará la tabla de frecuencia de la variable <code>VTAS</code> en millones de dólares, del conjunto de datos trabajado en la sección <a href="primerR.html#primerR">2.4</a>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(agricolae)
<span class="kw">library</span>(dplyr)

h2&lt;-<span class="kw">with</span>(big4size,<span class="kw">graph.freq</span>(VTAS<span class="op">/</span><span class="dv">1000000</span>,<span class="dt">plot=</span><span class="ot">FALSE</span>));

h2 =<span class="st"> </span><span class="kw">table.freq</span>(h2)

h3 &lt;-<span class="st"> </span>h2 <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Clase =</span> <span class="kw">paste</span>(<span class="st">&quot;[&quot;</span>,Lower,<span class="st">&quot;,&quot;</span>,Upper,<span class="st">&quot;)&quot;</span>),    
        <span class="st">&quot;Marca de Clase&quot;</span>  =<span class="st">  </span>Main,
        <span class="dt">Frec. =</span> Frequency,
        <span class="st">&quot;Frec. Rel.&quot;</span> =<span class="st"> </span>Percentage,
        <span class="st">&quot;Frec. Acu.&quot;</span> =<span class="st"> </span>CF,
        <span class="st">&quot;Rel. Acu.&quot;</span> =<span class="st"> </span>CPF )  <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(<span class="op">-</span><span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">7</span>))</code></pre></div>
<table>
<caption>
<span id="tab:tabla3">Tabla 2.3: </span>Tabla de Frecuencia de las Ventas
</caption>
<thead>
<tr>
<th style="text-align:left;">
Clase
</th>
<th style="text-align:right;">
Marca de Clase
</th>
<th style="text-align:right;">
Frec.
</th>
<th style="text-align:right;">
Frec. Rel.
</th>
<th style="text-align:right;">
Frec. Acu.
</th>
<th style="text-align:right;">
Rel. Acu.
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
[ 0 , 165.76 )
</td>
<td style="text-align:right;">
82.88
</td>
<td style="text-align:right;">
2099
</td>
<td style="text-align:right;">
93.0
</td>
<td style="text-align:right;">
2099
</td>
<td style="text-align:right;">
93.0
</td>
</tr>
<tr>
<td style="text-align:left;">
[ 165.76 , 331.52 )
</td>
<td style="text-align:right;">
248.64
</td>
<td style="text-align:right;">
83
</td>
<td style="text-align:right;">
3.7
</td>
<td style="text-align:right;">
2182
</td>
<td style="text-align:right;">
96.7
</td>
</tr>
<tr>
<td style="text-align:left;">
[ 331.52 , 497.28 )
</td>
<td style="text-align:right;">
414.40
</td>
<td style="text-align:right;">
35
</td>
<td style="text-align:right;">
1.6
</td>
<td style="text-align:right;">
2217
</td>
<td style="text-align:right;">
98.3
</td>
</tr>
<tr>
<td style="text-align:left;">
[ 497.28 , 663.04 )
</td>
<td style="text-align:right;">
580.16
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
0.8
</td>
<td style="text-align:right;">
2234
</td>
<td style="text-align:right;">
99.0
</td>
</tr>
<tr>
<td style="text-align:left;">
[ 663.04 , 828.8 )
</td>
<td style="text-align:right;">
745.92
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.0
</td>
<td style="text-align:right;">
2234
</td>
<td style="text-align:right;">
99.0
</td>
</tr>
<tr>
<td style="text-align:left;">
[ 828.8 , 994.56 )
</td>
<td style="text-align:right;">
911.68
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
0.3
</td>
<td style="text-align:right;">
2241
</td>
<td style="text-align:right;">
99.3
</td>
</tr>
<tr>
<td style="text-align:left;">
[ 994.56 , 1160.32 )
</td>
<td style="text-align:right;">
1077.44
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
0.5
</td>
<td style="text-align:right;">
2253
</td>
<td style="text-align:right;">
99.9
</td>
</tr>
<tr>
<td style="text-align:left;">
[ 1160.32 , 1326.08 )
</td>
<td style="text-align:right;">
1243.20
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.0
</td>
<td style="text-align:right;">
2253
</td>
<td style="text-align:right;">
99.9
</td>
</tr>
<tr>
<td style="text-align:left;">
[ 1326.08 , 1491.84 )
</td>
<td style="text-align:right;">
1408.96
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.0
</td>
<td style="text-align:right;">
2253
</td>
<td style="text-align:right;">
99.9
</td>
</tr>
<tr>
<td style="text-align:left;">
[ 1491.84 , 1657.6 )
</td>
<td style="text-align:right;">
1574.72
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.0
</td>
<td style="text-align:right;">
2253
</td>
<td style="text-align:right;">
99.9
</td>
</tr>
<tr>
<td style="text-align:left;">
[ 1657.6 , 1823.36 )
</td>
<td style="text-align:right;">
1740.48
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0.1
</td>
<td style="text-align:right;">
2255
</td>
<td style="text-align:right;">
100.0
</td>
</tr>
<tr>
<td style="text-align:left;">
[ 1823.36 , 1989.12 )
</td>
<td style="text-align:right;">
1906.24
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.0
</td>
<td style="text-align:right;">
2256
</td>
<td style="text-align:right;">
100.0
</td>
</tr>
</tbody>
</table>
<p>De la tabla <a href="tablas-de-frecuencia.html#tab:tabla3">2.3</a> se obsserva que el <span class="math inline">\(93\%\)</span> de las empresas realiza ventas entre 0 y <span class="math inline">\(165.76\)</span> millones. El <span class="math inline">\(99\%\)</span> de las empresas es decir <span class="math inline">\(2234\)</span> tiene ventas menores a <span class="math inline">\(663.04\)</span> millones de dólares, esto se lo puede ver en la columna de frecuencias acumuladas relativas. Además, solo una empresa tiene ventas entre <span class="math inline">\(1823.36\)</span> y <span class="math inline">\(1989.12\)</span> millones. Finalmente vamos a exportar la tabla de frecuencia en el archivo <code>tablas.xlsx</code>. La opción <code>append = TRUE</code> sirve para añadir una nueva hoja de cálculo al libro.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(xlsx)
h3 =<span class="st"> </span><span class="kw">as.data.frame</span>(h3)
<span class="kw">write.xlsx</span>(h3, <span class="st">&quot;tablas.xlsx&quot;</span>, <span class="dt">sheetName =</span> <span class="st">&quot;frec_ventas&quot;</span>, <span class="dt">row.names =</span> <span class="ot">FALSE</span>,<span class="dt">append=</span><span class="ot">TRUE</span>)</code></pre></div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="medidas-de-dispersion.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="tablas-de-contingencia.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["estadistica.pdf", "estadistica.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
